name: Publish package on NPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
        id: package-version

      - name: Create Git Tag
        uses: actions/github-script@v6
        env:
          TAG: v${{ steps.package-version.outputs.current-version}}
        with:
          github-token: ${{ github.token }}
          script: |
            const {TAG} = process.env
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${TAG}`,
              sha: context.sha
            })
            
      - uses: actions/setup-node@v2
        with:
          node-version: 21.x
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
